name: dem
channels:
  - conda-forge
  - nodefaults  # force everything to come from conda-forge channel
dependencies:
  - python==3.10.12
  - gdal==3.8.5
  - sardem~=0.11  # to download and crop the Copernicus DEM
  - scalene~=1.5.38
